Contact Form and Nodemailer
MathSocUNSW/mathsoc-website pull request #316
Opened 2022-05-19 13:43 UTC by AndersonPech

Implemented nodemailer api in api/mailer
Fixed styling using mixins in styles/contact.module.css
Form implementation in pages/contact

2022-05-22 03:51 UTC, jlin2002 requested changes
Check comments I left throughout

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/api/mailer.tsx
> +        user: process.env.EMAIL_API_EMAIL,
Rename to CONTACT_EMAIL and CONTACT_PASSWORD

2022-05-22 03:51 UTC, jlin2002 commented on src/data/contactData.ts
> +export interface Contacts {
Rename type to Contact.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/api/mailer.tsx
> +  } catch (error: any) {
Maybe look at this [stack overflow post](https://stackoverflow.com/questions/54649465/how-to-do-try-catch-and-finally-statements-in-typescript) to avoid use of any. Send back the error message to display to the user.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/api/mailer.tsx
> +    res.status(500).send({ error: res });
Why is the err field set to res?

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/api/mailer.tsx
> +      "First Name: " +
Use template literals.
Also, you can write something more natural like `Message from ${firstName} ${lastName} <${email}> via MathSoc website: ` as opposed to "New contact form request..." etc..

2022-05-22 03:51 UTC, jlin2002 commented on src/data/contactData.ts
> +  firstname: string;
Stick to camelCase.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/contact.tsx
> +  const handleChange = (event: any) => {
Check out this [stack overflow post](https://stackoverflow.com/questions/40676343/typescript-input-onchange-event-target-value) to properly type event handlers.

2022-05-22 03:51 UTC, jlin2002 commented on src/data/contactData.ts
> +  lastname: string;
Still think it's better to just have a name field for the contact form -- we can avoid the gap issue and also not everyone has a last name.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/contact.tsx
> +      } catch (err: any) {
Same as above.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/contact.tsx
> +                    <Typography variant="h6">First Name:</Typography>
Make this component a label using the 'component' attribute that comes with typography. See [mui documentation](https://mui.com/material-ui/react-typography/#changing-the-semantic-element). Give each input an id and use the 'htmlFor' attribute on the label to make the form more accessible.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/contact.tsx
> +                  <div style={{ width: "100%" }}>
Avoid inline styles. Give each div a class name.

2022-05-22 03:51 UTC, jlin2002 commented on src/pages/contact.tsx
> +            <div className={styles.contactForm}>
Why can't we directly style the form as opposed to putting another div around the contact form?

2022-06-04 01:02 UTC, jlin2002 requested changes

2022-06-04 01:02 UTC, jlin2002 commented on src/components/ContactPageBody.tsx
> +import React from "react";
Why can't you use the PageBody component?

2022-06-04 01:02 UTC, jlin2002 commented on src/components/ContactBox.tsx
> +import React from "react";
This is largely copied and pasted over from WholePageBox. Consider making WholePageBox component take in an optional prop boxType that is an enum:
```TypeScript
enum BoxType {
    FULL_WIDTH,
    HALF_WIDTH
}
```
If boxType is HALF_WIDTH, apply a class called halfBoxBody containing styles for the box.

2022-06-04 01:02 UTC, jlin2002 commented on src/styles/contactpagebox.module.scss
> +.cardBackground {
This is largely copied and pasted over from the WholePageBox module. Consider using making use of mixins.

2022-06-17 11:57 UTC, AndersonPech commented
- Modified pages/contact
- Included api/mailer
- Modified styles/contact.module.scss

2022-06-17 11:57 UTC, merged